codecov:
  require_ci_to_pass: true
coverage:
  precision: 2
  round: down
  range: 70..100
  status:
    project:
      default:
        target: 85%
        threshold: 1%
        paths:
          - src/
    patch:
      default:
        target: 90%
        threshold: 1%
comment:
  layout: "diff"
  behavior: default
  require_changes: true

ignore:
  - tests/
  - docs/
  - .devcontainer/
  - dist/
  - node_modules/
  - "*.config.js"
  - "*.config.ts"
